# Build and run tests on push to any branch except master

name: check-branch

on:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
